#include "Animation.h"
#include "../FileReading/JsonHelpers.h"

namespace Degen
{
	namespace Component
	{
		Animation::Animation() : iComponent(ANIMATION_COMPONENT),
			default_animation(""),
			default_blend_time(0.f),
			blending_time(0.f),
			playing_animation(""),
			playing_animation_blend_time(0.f),
			play_through(false),
			lock_animation(false),
			next_animation(""),
			next_animation_blend_time(0.f),
			relitive_matrix(1.f)
		{
		}

		bool Animation::Deserialize(Json::Value& json)
		{
			JsonHelp::Set(json["default_animation"], default_animation);
			JsonHelp::Set(json["default_blend_time"], default_blend_time);
			JsonHelp::Set(json["playing_animation"], playing_animation);
			JsonHelp::Set(json["playing_animation_blend_time"], playing_animation_blend_time);
			JsonHelp::Set(json["play_through"], play_through);
			JsonHelp::Set(json["lock_animation"], lock_animation);

			JsonHelp::Set(json["next_animation"], next_animation);
			JsonHelp::Set(json["next_animation_blend_time"], next_animation_blend_time);

			//bone transforms and relitive matrix generated by animator

			return true;
		}
	}
}

